/**
 * Centralized configuration
 * Cette API permet de définir les services relatif à la configuration
 *
 * OpenAPI spec version: 0.0.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Definition { 
    /**
     * Nom unique de la variable dans une application
     */
    name?: string;
    /**
     * Libellé présenté à l'utilisateur lors de la mise à jour
     */
    label?: string;
    /**
     * Texte décrivant la variable. Peut aussi servir de tooltip dans l'IHM de gestion
     */
    description?: string;
    /**
     * Type de la variable
     */
    type?: Definition.TypeEnum;
    /**
     * Expression régulière permettant de valider la variable
     */
    format?: string;
    /**
     * valeur par défaut de la variable si elle n'est pas renseigné.
     */
    _default?: string;
    /**
     * Attribut permettant de savoir si la variable peut être modifié par l'utilisateur ou si elle n'est seulement disponible en lecture
     */
    readOnly?: boolean;
    /**
     * Attribut permettant de savoir si la variable peut être lu sans que l'utilisateur ait le droit de la modifier. Un appel avec le token applicatif retrouvera aussi la valeur.
     */
    restricted?: boolean;
    /**
     * Attribut permettant de savoir si la variable peut être changé à chaud ou non.
     */
    restartNeeded?: boolean;
    /**
     * 
     */
    scope?: Definition.ScopeEnum;
    /**
     * Attribut permettant de définir le niveau de sécurité que l'utilisateur doit avoir afin de pouvoir la mettre à jour
     */
    level?: Definition.LevelEnum;
}
export namespace Definition {
    export type TypeEnum = 'STRING' | 'INT' | 'BOOL' | 'ARRAY' | 'FLOAT' | 'ENUM' | 'DATE';
    export const TypeEnum = {
        STRING: 'STRING' as TypeEnum,
        INT: 'INT' as TypeEnum,
        BOOL: 'BOOL' as TypeEnum,
        ARRAY: 'ARRAY' as TypeEnum,
        FLOAT: 'FLOAT' as TypeEnum,
        ENUM: 'ENUM' as TypeEnum,
        DATE: 'DATE' as TypeEnum
    };
    export type ScopeEnum = 'USER' | 'NODE' | 'GROUP';
    export const ScopeEnum = {
        USER: 'USER' as ScopeEnum,
        NODE: 'NODE' as ScopeEnum,
        GROUP: 'GROUP' as ScopeEnum
    };
    export type LevelEnum = 'USER' | 'IT' | 'SUPPORT' | 'ACETIAM';
    export const LevelEnum = {
        USER: 'USER' as LevelEnum,
        IT: 'IT' as LevelEnum,
        SUPPORT: 'SUPPORT' as LevelEnum,
        ACETIAM: 'ACETIAM' as LevelEnum
    };
}

